apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-deployment
spec:
  selector:
    matchLabels:
      app: apicurio-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio-registry
          image: apicurio/apicurio-registry-mem:1.3.2.Final
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry
spec:
  selector:
    app: apicurio-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  type: NodePort